services:
  environment:
    build:
      context: environment
      dockerfile: Dockerfile
    container_name: environment
    # ports:
    #   - 3000:3000
    #   - 8080:8080
    volumes:
      - ..:/workspace:cached,rw
      - /var/run/docker.sock:/var/run/docker.sock:cached
    working_dir: /workspace
    tty: true
    stdin_open: true

  db:
    image: postgres:16-alpine
    container_name: postgres
    depends_on:
      - environment
    env_file:
      - path: .env
        required: true
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  db_data:
    driver: local
