# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI - Quality Gate

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y make gettext-base
          make env

      - name: Build Devcontainer
        uses: devcontainers/ci@v0.3

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Hadolint Check
        uses: hadolint/hadolint-action@v3.1.0
        if: always()
        with:
          recursive: true

      - name: TSC
        if: always()
        run: bun tsc --noEmit

      - name: Biome CI
        if: always()
        run: bunx @biomejs/biome ci .

      - name: Drizzle-Kit Check
        if: always()
        run: bun run --cwd src/db db:check
